.PHONY: clean All

All:
	@echo "----------Building project:[ HelloProject - Debug ]----------"
	@cd "HelloProject" && "$(MAKE)" -f  "HelloProject.mk"
clean:
	@echo "----------Cleaning project:[ HelloProject - Debug ]----------"
	@cd "HelloProject" && "$(MAKE)" -f  "HelloProject.mk" clean
